import { useState, useEffect, useRef } from 'react'
import { useNavigate } from 'react-router-dom'
import { ChevronLeft, Loader2, Image as ImageIcon, AlertTriangle, Trash2, RefreshCcw, Upload } from 'lucide-react'
import { useAuth } from '../contexts/AuthContext'
import { supabase, uploadImageToStorage } from '../lib/supabase'
import { useStore } from '../store/useStore'
import { generateSceneImage } from '../lib/togetherAi'
import { generateNanoBananaImage } from '../lib/nanoBanana'
import { getTravelCompanion, TRAVEL_COMPANIONS } from '../data/travel/companions'

const BENCH_STORAGE_KEY = 'chaptr-image-bench-inputs'

function isEphemeralLike(u: string): boolean {
  return u.includes('api.together.ai/shrt') || u.includes('api.together.xyz/shrt') || u.includes('together.ai/imgproxy')
}

const SG = "'Space Grotesk', sans-serif"

const DEFAULT_PROMPT = `Anime illustration, two people in the foreground, posing for a photo together at an airport gate: a young man on the left and a young woman on the right, both smiling at the camera, both wearing backpacks, excited to travel to Bangkok. Behind them, large terminal windows show a plane on the tarmac in warm golden hour light. No text, no signs, no departure boards`

// Travel-mode companions only. Derived from TRAVEL_COMPANIONS so this stays in
// sync as new travel companions are added — no manual maintenance.
const TRAVEL_COMPANION_OPTIONS = TRAVEL_COMPANIONS
  .filter((c) => !!c.character.staticPortrait)
  .map((c) => ({ name: c.character.name, url: c.character.staticPortrait! }))

type ModelId = 'flux2' | 'kontext' | 'schnell' | 'nano-banana-2' | 'nano-banana-pro' | 'nano-banana'

const MODEL_LABELS: Record<ModelId, string> = {
  'flux2': 'FLUX.2 Pro',
  'kontext': 'Kontext Pro',
  'schnell': 'Schnell',
  'nano-banana-2': 'Nano Banana 2 (Gemini 3.1 Flash)',
  'nano-banana-pro': 'Nano Banana Pro (Gemini 3 Pro)',
  'nano-banana': 'Nano Banana (Gemini 2.5)',
}

const SHORT_MODEL_LABELS: Record<ModelId, string> = {
  'flux2': 'FLUX.2',
  'kontext': 'Kontext',
  'schnell': 'Schnell',
  'nano-banana-2': 'Nano Banana 2',
  'nano-banana-pro': 'Nano Banana Pro',
  'nano-banana': 'Nano Banana',
}

// Public per-image pricing in USD as of Apr 2026. Approximate; useful for
// rough cost-at-scale comparison, not billing. Gemini prices are 1K
// (1024x1024) tier — bench renders at 768x576 which falls into the same
// or lower bracket. Source: ai.google.dev/gemini-api/docs/pricing
const MODEL_COST_USD: Record<ModelId, number> = {
  'flux2': 0.03,             // FLUX.2 [pro] via together.ai/pricing
  'kontext': 0.04,           // FLUX.1 Kontext [pro] via together.ai/pricing
  'schnell': 0.0027,         // FLUX.1 [schnell] via together.ai/pricing
  'nano-banana': 0.039,      // Gemini 2.5 Flash Image — original Nano Banana
  'nano-banana-2': 0.067,    // Gemini 3.1 Flash Image Preview — newer Flash tier
  'nano-banana-pro': 0.134,  // Gemini 3 Pro Image — premium
}

const NANO_MODEL_IDS: Partial<Record<ModelId, string>> = {
  'nano-banana-2': 'gemini-3.1-flash-image-preview',
  'nano-banana-pro': 'gemini-3-pro-image-preview',
  'nano-banana': 'gemini-2.5-flash-image',
}

// Audit table: every place in the app that calls an image-gen model.
// Source-of-truth reference for admins comparing model choices and prompts.
// When the production code changes, update this table to match.
interface ImageGenAction {
  feature: string
  category: 'Twin' | 'Travel' | 'Story' | 'Chat reaction' | 'Cast'
  trigger: string
  source: string  // file:line
  model: string   // tier as actually used in prod
  references: 'twin + companion' | 'twin only' | 'companion only' | 'none'
  promptTemplate: string
  // Optional. Set when promptTemplate is a *description* of where the prompt
  // comes from at runtime (e.g. "scene.imagePrompt generated by Claude") rather
  // than a real prompt. The bench loads a random entry from samplePrompts so
  // model output reflects production-shaped input, not the doc string. Multiple
  // entries enable a "shuffle sample" button to test breadth across the prompt
  // space the action actually produces in production.
  samplePrompts?: string[]
  notes?: string
}

const IMAGE_GEN_AUDIT: ImageGenAction[] = [
  {
    feature: 'Stylize twin selfie',
    category: 'Twin',
    trigger: 'User uploads selfie during twin creation/edit',
    source: 'src/lib/togetherAi.ts:272 (stylizeSelfie)',
    model: 'Nano Banana (gemini-2.5-flash-image)',
    references: 'twin only',
    promptTemplate: 'Transform this photo into an anime-style portrait illustration. Keep the exact same person, face, gender, facial features, glasses if present, hairstyle, and expression. Apply a clean anime art style with soft studio lighting, expressive eyes, and detailed hair. Clean simple background.',
    notes: 'Routed through /api/nano-banana. Returns base64 data URL → uploaded to Supabase Storage → permanent URL on twin.',
  },
  {
    feature: 'Travel departure scene',
    category: 'Travel',
    trigger: 'Trip starts (DepartureScreen mounts, no existing image)',
    source: 'src/components/travel/DepartureScreen.tsx:94',
    model: 'Nano Banana (gemini-2.5-flash-image)',
    references: 'twin + companion',
    promptTemplate: 'Anime illustration, two people in the foreground, posing for a photo together at an airport gate: a {protagNoun} on the left and a {compNoun} ({compShort}) on the right, both smiling at the camera, both wearing backpacks, excited to travel to {city}...',
    notes: 'Calls /api/nano-banana directly with both reference images. Falls back to a text-only city skyline prompt if no refs are available.',
  },
  {
    feature: 'Travel scene (per day/scene)',
    category: 'Travel',
    trigger: 'Day advances or scene changes during a trip',
    source: 'src/pages/TravelReaderPage.tsx:1023',
    model: 'Nano Banana (gemini-2.5-flash-image)',
    references: 'twin + companion',
    promptTemplate: 'Built inline at TravelReaderPage.tsx:1027 from scene.timeOfDay, scene.location, destination.city, and the first ~300 chars of the streamed scene prose: `anime illustration, cel-shaded, cinematic wide shot, {timeOfDay} atmosphere in {location}, {city}. {proseSnippet}. Detailed background, atmospheric lighting, vibrant anime art`',
    samplePrompts: [
      'anime illustration, cel-shaded, cinematic wide shot, golden hour atmosphere in Wat Pho temple grounds, Bangkok. They walk slowly between weathered stone columns as monks chant somewhere out of sight, sunlight cutting through drifting incense smoke, the gold leaf on a reclining Buddha glowing behind them. Detailed background, atmospheric lighting, vibrant anime art',
      'anime illustration, cel-shaded, cinematic wide shot, late night atmosphere on a Shibuya rooftop bar, Tokyo. The crossing pulses red and electric blue far below them, neon signage reflecting on rain-slick streets, a cold beer sweating on the railing as the city hums. Detailed background, atmospheric lighting, vibrant anime art',
      'anime illustration, cel-shaded, cinematic wide shot, early morning atmosphere in the Arashiyama bamboo grove, Kyoto. Mist clings low to the path between impossibly tall green stalks, the only sound the soft creak of bamboo in the wind and their footsteps on packed earth. Detailed background, atmospheric lighting, vibrant anime art',
      'anime illustration, cel-shaded, cinematic wide shot, dusk atmosphere along the Seine riverside, Paris. Bouquinistes are closing their green stalls as the lamps flicker on along the quay, Notre-Dame silhouetted against a lavender sky, the river catching the last of the light. Detailed background, atmospheric lighting, vibrant anime art',
      'anime illustration, cel-shaded, cinematic wide shot, midday atmosphere on the Tegalalang rice terrace path, Bali. Emerald paddies cascade down the valley in stepped curves, a farmer in a conical hat tending a row in the distance, the air thick with humidity and the smell of wet earth. Detailed background, atmospheric lighting, vibrant anime art',
      'anime illustration, cel-shaded, cinematic wide shot, twilight atmosphere at the Sky Lagoon geothermal pool, Reykjavík. Steam coils off the dark mineral water as the sky stripes pink and pale green with the start of an aurora, the cliff edge dropping away to the North Atlantic just beyond the infinity edge. Detailed background, atmospheric lighting, vibrant anime art',
    ],
    notes: 'Routes through generateSceneImage → /api/nano-banana. Companion ref dropped when scene.protagonistVisible is false. 6 sample variants spanning cities/times of day for shuffle testing.',
  },
  {
    feature: '"Show me" chat action',
    category: 'Travel',
    trigger: 'User taps 📸 Show me button in trip chat',
    source: 'src/pages/TravelReaderPage.tsx:649 (handleShowMe)',
    model: 'Nano Banana (gemini-2.5-flash-image)',
    references: 'twin + companion',
    promptTemplate: 'anime illustration, cel-shaded, cinematic scene: {lastCompanionMsgSnippet}. Setting: {locationContext}. Atmospheric lighting, detailed background, vibrant anime art',
    samplePrompts: [
      'anime illustration, cel-shaded, cinematic scene: The market is unreal — vendors yelling, food smoking, fairy lights everywhere. I think you should try the pad thai from the corner stall. Setting: Chatuchak Weekend Market, Bangkok. Atmospheric lighting, detailed background, vibrant anime art',
      'anime illustration, cel-shaded, cinematic scene: This place is hidden behind a noodle shop, but inside it is glowing with paper lanterns and the bartender is pouring something on fire. You have to see this. Setting: a speakeasy in Shimokitazawa, Tokyo. Atmospheric lighting, detailed background, vibrant anime art',
      'anime illustration, cel-shaded, cinematic scene: Look at the steam rising off the spring — and the moss on the rocks is electric green. Slip in slowly, the mineral water is hotter than it looks. Setting: a mountain onsen in Hakone, Japan. Atmospheric lighting, detailed background, vibrant anime art',
      'anime illustration, cel-shaded, cinematic scene: I told you the canals get magical at night. The boats are strung with lights and someone is playing a lute on the bridge. Setting: a quiet canal in Cannaregio, Venice. Atmospheric lighting, detailed background, vibrant anime art',
      'anime illustration, cel-shaded, cinematic scene: This is the rooftop I was telling you about. The whole city is below us — and that flame on the horizon is from the night fire ceremony at the temple. Setting: a guesthouse rooftop in Ubud, Bali. Atmospheric lighting, detailed background, vibrant anime art',
    ],
    notes: 'Routes through generateTravelImage → generateSceneImage → /api/nano-banana. Visualizes the last companion message — pulled live from chat history.',
  },
  {
    feature: '"Take a selfie" chat action',
    category: 'Travel',
    trigger: 'User taps 🤳 Selfie button in trip chat',
    source: 'src/pages/TravelReaderPage.tsx:824 (handleSelfie)',
    model: 'Nano Banana (gemini-2.5-flash-image)',
    references: 'twin + companion',
    promptTemplate: 'anime illustration, cel-shaded, selfie taken by {playerGender}, close-up selfie with {companionDesc}, both smiling at camera, peace signs, in {locationContext}, {activityHint}. Phone camera perspective, slight wide-angle distortion, warm natural lighting, candid happy energy, vibrant anime art',
    notes: 'Routes through generateTravelImage → generateSceneImage → /api/nano-banana. Reliable identity match because gender + companion description are baked into the SCENE prompt, not just the wrapper preamble.',
  },
  {
    feature: '"Buy a gift" chat action',
    category: 'Travel',
    trigger: 'User taps 🎁 Buy a gift button in trip chat',
    source: 'src/pages/TravelReaderPage.tsx:701 (handleBuyGift)',
    model: 'Nano Banana (gemini-2.5-flash-image)',
    references: 'companion only',
    promptTemplate: 'Anime-style portrait illustration. The reference image shows the travel companion — render them with the same face, hair, and gender. {buildReactionImagePrompt(companionVisualDesc, "mystery-box", "gift")} → {base portrait}, eyes wide with surprise and delight, holding a small gift box, mouth slightly open in excitement, playful curious expression, warm colorful lighting',
    notes: 'Generates a reaction PORTRAIT (not a scene) via /api/nano-banana with the companion portrait as a single reference for face consistency. Falls back to a text-only prompt if no companion portrait is available.',
  },
  {
    feature: '"Hold hands" chat action',
    category: 'Travel',
    trigger: 'User taps 💕 Hold hands button in trip chat',
    source: 'src/pages/TravelReaderPage.tsx:773 (handleHoldHands)',
    model: 'Nano Banana (gemini-2.5-flash-image)',
    references: 'twin + companion',
    promptTemplate: 'anime illustration, cel-shaded, two people walking together holding hands from behind on a beautiful street in {locationContext}. {playerGender} and {companionDesc}. Close-up on their intertwined hands, warm golden hour lighting, soft bokeh, romantic moment, vibrant anime art',
    samplePrompts: [
      'anime illustration, cel-shaded, two people walking together holding hands from behind on a beautiful street in Asakusa, Tokyo. a young man and 22-year-old Japanese woman with long dark hair, gentle smile. Close-up on their intertwined hands, warm golden hour lighting, soft bokeh, romantic moment, vibrant anime art',
      'anime illustration, cel-shaded, two people walking together holding hands from behind on a cobbled lane in Montmartre, Paris. a young man and 21-year-old French woman with chestnut waves, soft amused expression. Close-up on their intertwined hands, warm golden hour lighting, soft bokeh, romantic moment, vibrant anime art',
      'anime illustration, cel-shaded, two people walking together holding hands from behind on a beachfront promenade in Seminyak, Bali. a young man and 23-year-old Indonesian woman with sun-kissed skin, soft smile. Close-up on their intertwined hands, warm golden hour lighting, soft bokeh, romantic moment, vibrant anime art',
      'anime illustration, cel-shaded, two people walking together holding hands from behind on a snow-dusted side street in Sapporo, Hokkaido. a young man and 22-year-old Japanese woman with long dark hair tucked into a wool scarf. Close-up on their intertwined hands, warm golden hour lighting, soft bokeh, romantic moment, vibrant anime art',
    ],
    notes: 'Routes through generateTravelImage → generateSceneImage → /api/nano-banana.',
  },
  {
    feature: '"Get a kiss" chat action',
    category: 'Travel',
    trigger: 'User taps 💋 Get a kiss button in trip chat',
    source: 'src/pages/TravelReaderPage.tsx:836 (handleGetKiss)',
    model: 'Nano Banana (gemini-2.5-flash-image)',
    references: 'twin + companion',
    promptTemplate: 'anime illustration, cel-shaded, romantic close-up of two people sharing a soft tender kiss in {locationContext}. {playerGender} and {companionDesc}. Eyes closed, gentle expressions, hands on cheeks, warm golden hour lighting, soft cinematic bokeh, intimate emotional moment, vibrant anime art, ONLY these two people in the image',
    samplePrompts: [
      'anime illustration, cel-shaded, romantic close-up of two people sharing a soft tender kiss on a quiet alley in Asakusa, Tokyo. a young man and 22-year-old Japanese woman with long dark hair, gentle expression. Eyes closed, gentle expressions, hands on cheeks, warm golden hour lighting, soft cinematic bokeh, intimate emotional moment, vibrant anime art, ONLY these two people in the image',
      'anime illustration, cel-shaded, romantic close-up of two people sharing a soft tender kiss on a footbridge over the Seine, Paris. a young man and 21-year-old French woman with chestnut waves, soft amused expression. Eyes closed, gentle expressions, hands on cheeks, warm golden hour lighting, soft cinematic bokeh, intimate emotional moment, vibrant anime art, ONLY these two people in the image',
      'anime illustration, cel-shaded, romantic close-up of two people sharing a soft tender kiss on a torchlit beach in Seminyak, Bali. a young man and 23-year-old Indonesian woman with sun-kissed skin, soft smile. Eyes closed, gentle expressions, hands on cheeks, warm golden hour lighting, soft cinematic bokeh, intimate emotional moment, vibrant anime art, ONLY these two people in the image',
      'anime illustration, cel-shaded, romantic close-up of two people sharing a soft tender kiss under falling snow in Otaru, Hokkaido. a young man and 22-year-old Japanese woman with long dark hair tucked into a wool scarf. Eyes closed, gentle expressions, hands on cheeks, warm golden hour lighting, soft cinematic bokeh, intimate emotional moment, vibrant anime art, ONLY these two people in the image',
    ],
    notes: 'Routes through generateTravelImage → generateSceneImage → /api/nano-banana. Affinity bumped by min 5 (vs 3 for Hold hands) since it\'s a stronger romantic beat.',
  },
  {
    feature: '"Cuddle" day-end action',
    category: 'Travel',
    trigger: 'User taps 💗 Cuddle button on the wind-down screen (end of day)',
    source: 'src/pages/TravelReaderPage.tsx (handleCuddle)',
    model: 'Nano Banana (gemini-2.5-flash-image)',
    references: 'twin + companion',
    promptTemplate: 'anime illustration, cel-shaded, romantic close-up of two people cuddling tenderly under a soft white duvet in a cozy hotel bed in {destination.city}. {playerGender} and {companionDesc}. Bare shoulders just visible above the sheets — the duvet pulled high across both of their chests so only their faces, hair, and shoulders are showing, everything below the collarbones tastefully hidden under the bedding. Foreheads touching, eyes closed peacefully, gentle content smiles, soft warm bedside lamplight, intimate post-romance tenderness, vibrant anime art, ONLY these two people in the image, modest tasteful framing, no exposed skin below the shoulders',
    samplePrompts: [
      'anime illustration, cel-shaded, romantic close-up of two people cuddling tenderly under a soft white duvet in a cozy hotel bed in Tokyo. a young man and 22-year-old Japanese woman with long dark hair, gentle expression. Bare shoulders just visible above the sheets — the duvet pulled high across both of their chests so only their faces, hair, and shoulders are showing, everything below the collarbones tastefully hidden under the bedding. Foreheads touching, eyes closed peacefully, gentle content smiles, soft warm bedside lamplight, intimate post-romance tenderness, vibrant anime art, ONLY these two people in the image, modest tasteful framing, no exposed skin below the shoulders',
      'anime illustration, cel-shaded, romantic close-up of two people cuddling tenderly under a thick white kakebuton in a cozy ryokan futon in Kyoto. a young man and 22-year-old Japanese woman with shoulder-length wavy hair, soft smile. Bare shoulders just visible above the bedding — the kakebuton pulled high across both of their chests so only their faces, hair, and shoulders are showing, everything below the collarbones tastefully hidden under the futon. Foreheads touching, eyes closed peacefully, gentle content smiles, paper lantern lamplight, intimate post-romance tenderness, vibrant anime art, ONLY these two people in the image, modest tasteful framing, no exposed skin below the shoulders',
      'anime illustration, cel-shaded, romantic close-up of two people cuddling tenderly under a soft white duvet in a cozy boutique hotel bed in Paris. a young man and 21-year-old French woman with chestnut waves, soft amused expression. Bare shoulders just visible above the sheets — the duvet pulled high across both of their chests so only their faces, hair, and shoulders are showing, everything below the collarbones tastefully hidden under the bedding. Foreheads touching, eyes closed peacefully, gentle content smiles, soft Parisian bedside lamplight, intimate post-romance tenderness, vibrant anime art, ONLY these two people in the image, modest tasteful framing, no exposed skin below the shoulders',
      'anime illustration, cel-shaded, romantic close-up of two people cuddling tenderly under a soft white duvet in a cozy beachfront villa bed in Seminyak, Bali. a young man and 23-year-old Indonesian woman with sun-kissed skin, soft smile. Bare shoulders just visible above the sheets — the duvet pulled high across both of their chests so only their faces, hair, and shoulders are showing, everything below the collarbones tastefully hidden under the bedding. Foreheads touching, eyes closed peacefully, gentle content smiles, soft lamplight with rattan shadows on the wall, intimate post-romance tenderness, vibrant anime art, ONLY these two people in the image, modest tasteful framing, no exposed skin below the shoulders',
    ],
    notes: 'Free for now; UI shows a strikethrough 50-gem cost as the future paid tier. Bumps affinity +5. Implied-undressed framing — bare shoulders visible, duvet covers everything from collarbones down. Some Gemini safety tunings may flag; if Nano Banana 2.5 refuses, fall back to 3.1 Flash for this action specifically. Result lives in a modal — not persisted on the trip yet, so it\'s lost on dismiss until Save-to-memories ships.',
  },
  {
    feature: '"Let\'s get closer" day-end action',
    category: 'Travel',
    trigger: 'User taps 🌹 Let\'s get closer button on the wind-down screen',
    source: 'src/pages/TravelReaderPage.tsx (handleGetCloser)',
    model: 'Nano Banana (gemini-2.5-flash-image)',
    references: 'twin + companion',
    promptTemplate: 'Randomized at runtime across 6 sensual-but-tasteful framings: Hand on shoulder · Deep kiss tangled sheets · After the shower making out · Pinned against the door · Dawn embrace · Fingers intertwined. Three of six are explicit kisses/make-outs (deep kiss, after-shower kiss, door-pinned kiss); three are slower intimacy beats. Each variant takes {playerGender}, {companionDesc}, {destination.city} and produces an anime cel-shaded close-up with explicit "modest tasteful framing" guardrails so chests/waist stay covered.',
    samplePrompts: [
      'anime illustration, cel-shaded, intimate close-up of two people lying face to face under a soft white duvet in a hotel bed in Tokyo, both undressed underneath the sheet. a young man and 22-year-old Japanese woman with long dark hair, gentle expression. Their fingers are intertwined above the sheet between them, the second person\'s free hand resting tenderly on the first\'s bare shoulder. Sheet draped low across their chests — for the woman in the pair: slight cleavage and bare collarbones visible above the sheet; for the man in the pair: bare upper chest and a hint of abs visible where the sheet sits at his ribcage. Both with soft lingering smiles, eyes half-lidded and looking into each other. Warm bedside lamplight, golden glow on bare skin, modest tasteful framing — the sheet still fully covers everything below the lower ribs, no nudity, slow-burning romantic tension, vibrant anime art, ONLY these two people in the image',
      'anime illustration, cel-shaded, intimate close-up of two people sharing a deep slow kiss in a hotel bed in Paris, both undressed beneath the tangled sheets. a young man and 21-year-old French woman with chestnut waves, soft amused expression. One leans over the other, dark hair falling forward to brush their cheek, sheets bunched around their lower bodies — for the woman in the pair: slight cleavage and a bare back visible from this angle; for the man in the pair: bare upper torso and a hint of side abs visible where the sheet has slipped. The second person\'s hand cupping the first\'s jaw. Eyes closed, lost in the moment, soft flushed cheeks, warm bedside lamplight on bare skin, modest tasteful framing — the sheet still covers everything below the waist, no nudity, intense romantic tenderness, vibrant anime art, ONLY these two people in the image',
      'anime illustration, cel-shaded, intimate close-up of two people in soft white bathrobes making out passionately in a hotel suite in Kyoto, just out of the shower. a young man and 22-year-old Japanese woman with shoulder-length wavy hair, soft smile. Mid-kiss with eyes closed, lost in each other, the second person\'s hand on the first\'s jaw drawing them in, the first\'s hand at the second\'s waist pulling them closer. Robes slightly damp, slipped off one bare shoulder of each, hair still wet at the tips. Steam drifting in from the bathroom door, warm amber lamplight, soft mist in the air, modest tasteful framing — robes covering everything important, hot urgent tenderness, vibrant anime art, ONLY these two people in the image',
      'anime illustration, cel-shaded, intimate close-up of two people making out against the inside of a hotel suite door in Tokyo, just stumbled in from outside. a young man and 22-year-old Japanese woman with long dark hair, slightly flushed expression. One has the other gently pinned to the door, both hands cradling their face, deep open-mouthed kiss, eyes closed, brows slightly drawn together with intensity. The pinned one\'s hands gripping the other\'s shirt at the waist, jackets and bags dropped on the floor beside them. Warm hallway lamplight bleeding past the doorway, soft cinematic shadows, fully clothed but with clothing slightly disheveled, urgent romantic hunger after a long evening out, vibrant anime art, ONLY these two people in the image',
      'anime illustration, cel-shaded, intimate close-up of two people sleeping wrapped in each other\'s arms at dawn in a hotel bed in Bali, both undressed beneath the sheets. a young man and 23-year-old Indonesian woman with sun-kissed skin, soft smile. The first lies on their side, the second curled around them from behind with one arm draped softly across their bare shoulder, fingers tracing along the first person\'s collarbone. Sheet draped to mid-chest — for the woman in the pair: bare shoulder blade and slight cleavage visible above the sheet; for the man in the pair: bare upper back and a hint of side abs visible. Both peacefully asleep with content half-smiles, pale blue and pink dawn light filtering through curtains glowing on bare skin, modest tasteful framing — the sheet still covers everything below the lower ribs, no nudity, quiet morning intimacy, vibrant anime art, ONLY these two people in the image',
      'anime illustration, cel-shaded, intimate overhead shot of two people lying side by side under a soft duvet in a hotel bed in Reykjavík, both undressed beneath the sheet. a young man and 24-year-old Icelandic woman with platinum-blonde hair, soft serious eyes. Their fingers laced together resting between them on the pillow, faces turned toward each other, eyes locked in a soft unspoken conversation, lips slightly parted. Sheet draped to mid-chest — for the woman in the pair: slight cleavage and bare collarbones visible above the sheet; for the man in the pair: bare upper chest and a hint of abs visible at the edge of the sheet. Dim warm bedside lamplight casting soft shadows across their faces and bare skin, modest tasteful framing — the sheet still covers everything below the lower ribs, no nudity, quiet romantic vulnerability, vibrant anime art, ONLY these two people in the image',
    ],
    notes: 'Step up from Cuddle (+8 affinity vs +5). Prompt is rolled randomly each tap from the variant pool; the modal caption shows the variant label so users can collect the different beats. Three of six framings are now active kissing/making out (Deep kiss · After-shower making out · Pinned against the door); three are slower intimacy beats. Models with stricter safety (sometimes Nano Banana 2.5) may soft-refuse the kiss-heavy variants — bench all 6 × 6 models to map reliable combos before locking the production pool.',
  },
  {
    feature: 'Day-start transition (no AI gen)',
    category: 'Travel',
    trigger: 'New day begins (handlePlayScene → setViewMode("day-start"))',
    source: 'src/components/travel/DayTransition.tsx:50 (type="start")',
    model: '— (uses static heroImage)',
    references: 'none',
    promptTemplate: '— DayTransition reuses destination.heroImage as the background. No image generation happens here.',
    notes: 'If you want a fresh dawn-over-{city} render per day, this is where to add a generateNanoBananaImage call.',
  },
  {
    feature: 'Day-end transition (no AI gen)',
    category: 'Travel',
    trigger: 'Last scene of day finished (handleNextScene → recap → setViewMode("day-end"))',
    source: 'src/components/travel/DayTransition.tsx:50 (type="end")',
    model: '— (uses static heroImage + already-generated scene thumbnails)',
    references: 'none',
    promptTemplate: '— DayTransition shows the destination heroImage darkened plus thumbnail recap of the day\'s scene images. No image generation happens here.',
    notes: 'If you want a fresh "city at night" or wind-down render per day, this is where to add a generateNanoBananaImage call.',
  },
  {
    feature: 'Story scene image',
    category: 'Story',
    trigger: 'Story step advances (mounts a step with sceneImagePrompt)',
    source: 'src/pages/StoryReaderPage.tsx:213',
    model: 'Nano Banana (gemini-2.5-flash-image)',
    references: 'twin only',
    promptTemplate: 'currentStep.sceneImagePrompt (defined per step in src/data/stories/<id>.ts)',
    samplePrompts: ['Anime style, a handsome Korean male idol with dark messy hair dancing intensely in a practice room with mirror walls, warm spotlight, focused expression, sweat on his brow, Seoul skyline through windows at dusk, other dancers in background'],
    notes: 'Routes through generateSceneImage → /api/nano-banana. Player only — companions described in text. Sample = SCENE_PROMPTS.rehearsal from storyData.ts.',
  },
  {
    feature: 'Story branch option preview',
    category: 'Story',
    trigger: 'Choice point reached in story',
    source: 'src/pages/StoryReaderPage.tsx:232',
    model: 'Nano Banana (gemini-2.5-flash-image)',
    references: 'twin only',
    promptTemplate: 'opt.imagePrompt (per choice option in story data)',
    samplePrompts: ['Anime style, two young people facing each other on a rooftop at night, one with dark messy hair looking intense, wind blowing, city lights sprawling behind them, emotional confrontation, K-drama climax'],
  },
  {
    feature: 'Reveal scene',
    category: 'Story',
    trigger: 'Story complete → reveal page loads',
    source: 'src/pages/RevealPage.tsx:54',
    model: 'Nano Banana (gemini-2.5-flash-image)',
    references: 'twin only',
    promptTemplate: 'Reveal-specific prompt built from playthrough state (RevealPage.tsx:50)',
    samplePrompts: ['Anime style, ethereal dream-like scene, two silhouettes connected by glowing threads of light, abstract Seoul cityscape in background, cosmic purple and pink tones, emotional, beautiful'],
  },
  {
    feature: 'NPC character portrait (AI-generated)',
    category: 'Chat reaction',
    trigger: 'Character first appears without staticPortrait',
    source: 'src/lib/togetherAi.ts:222 (generateCharacterPortrait)',
    model: 'Schnell (FLUX.1-schnell)',
    references: 'none',
    promptTemplate: 'character.portraitPrompt (defined per character in src/data/characters.ts)',
    samplePrompts: ['Anime style portrait of a handsome 22 year old Korean male, warm bright smile showing teeth, slightly tousled dark brown hair with subtle highlights, friendly expressive brown eyes, wearing a casual denim jacket over a white t-shirt, one small silver hoop earring, soft studio lighting, clean dark background, high quality anime art style, detailed face, K-drama aesthetic, approachable and fun energy'],
    notes: 'Most main characters have staticPortrait — this path only runs for characters without one. Sample = Min-jun portraitPrompt.',
  },
  {
    feature: 'Reaction image — love letter',
    category: 'Chat reaction',
    trigger: 'Send a love letter chat action',
    source: 'src/data/chatActions.ts:266 (buildReactionImagePrompt)',
    model: 'Schnell',
    references: 'none',
    promptTemplate: '{base portrait}, holding a handwritten letter close to their chest, eyes soft and glistening with emotion, gentle blush on cheeks, tender surprised smile, warm intimate lighting, clean soft-focus background, high quality anime art style',
  },
  {
    feature: 'Reaction image — serenade',
    category: 'Chat reaction',
    trigger: 'Serenade chat action',
    source: 'src/data/chatActions.ts:266',
    model: 'Schnell',
    references: 'none',
    promptTemplate: '{base portrait}, eyes closed with a peaceful moved expression, hand over heart, soft blush, listening to music, dreamy warm lighting, deeply touched',
  },
  {
    feature: 'Reaction image — comfort (hug)',
    category: 'Chat reaction',
    trigger: 'Comfort chat action',
    source: 'src/data/chatActions.ts:266',
    model: 'Schnell',
    references: 'none',
    promptTemplate: '{base portrait}, arms open reaching out for a hug, soft vulnerable eyes glistening with tears, gentle grateful smile, warm golden lighting, emotionally moved',
  },
  {
    feature: 'Reaction image — mystery box (gift)',
    category: 'Chat reaction',
    trigger: 'Send a gift chat action',
    source: 'src/data/chatActions.ts:266',
    model: 'Schnell',
    references: 'none',
    promptTemplate: '{base portrait}, eyes wide with surprise and delight, holding a small gift box, mouth slightly open in excitement, playful curious expression, warm colorful lighting',
  },
  {
    feature: 'Reaction image — extend trip',
    category: 'Chat reaction',
    trigger: 'Stay 2 more days chat action',
    source: 'src/data/chatActions.ts:266',
    model: 'Schnell',
    references: 'none',
    promptTemplate: '{base portrait}, blushing deeply, hands clasped together near face, eyes sparkling with joyful disbelief, genuinely overwhelmed happy smile, soft warm golden lighting, emotionally touched and flustered',
  },
  {
    feature: 'Story romantic action scene (e.g. coffee)',
    category: 'Chat reaction',
    trigger: 'Chat action returns sceneImagePrompt',
    source: 'src/components/ChatScene.tsx:452',
    model: 'Nano Banana (gemini-2.5-flash-image)',
    references: 'twin only',
    promptTemplate: 'result.sceneImagePrompt (returned by Claude during chat action; built in src/hooks/useChatActions.ts)',
    samplePrompts: ['Anime illustration, cel-shaded, two people at a cozy café: a young person handing a warm coffee to a handsome 22-year-old Korean man with messy dark hair and warm brown eyes, warm smiles, gentle steam rising from the cup, soft warm café lighting, intimate casual moment, vibrant anime art, ONLY these two people in the image'],
  },
  {
    feature: 'Cast chat gift / reaction',
    category: 'Cast',
    trigger: 'Cast chat: send gift / kiss / etc',
    source: 'src/pages/CastChatPage.tsx:233,299',
    model: 'Schnell',
    references: 'none',
    promptTemplate: 'result.giftImagePrompt or result.reactionImagePrompt (from Claude tool call)',
    samplePrompts: ['Anime style, close-up of hands holding a fresh bouquet of colorful flowers wrapped in craft paper, soft warm lighting, romantic atmosphere, high quality illustration, no face visible, gift-giving moment'],
  },
  {
    feature: 'Cast group chat reaction',
    category: 'Cast',
    trigger: 'Cast group chat: romantic action targeting one character',
    source: 'src/pages/CastGroupChatPage.tsx:345',
    model: 'Schnell',
    references: 'none',
    promptTemplate: 'result.reactionImagePrompt',
    samplePrompts: ['Anime style portrait of a beautiful 22 year old Korean female K-pop idol, blushing deeply with hands clasped near her face, eyes sparkling with joyful disbelief, genuinely overwhelmed happy smile, soft warm golden lighting, emotionally touched and flustered, clean dark background, high quality anime art style'],
  },
]

interface Result {
  url?: string
  error?: string
  elapsedMs?: number
}

export function AdminImageBenchPage() {
  const navigate = useNavigate()
  const characters = useStore((s) => s.characters)
  const activeCharId = useStore((s) => s.activeCharacterId)
  const deleteCharacter = useStore((s) => s.deleteCharacter)
  const customCompanions = useStore((s) => s.customCompanions)
  const activeChar = characters.find((c) => c.id === activeCharId) ?? characters[0]
  const { user } = useAuth()
  const [isResetting, setIsResetting] = useState(false)

  // Twins-only reset: wipes just the character array + active id. Keeps
  // trips, stories, moments, gems, etc. so you don't lose play history
  // just to fix a corrupted character record. The trips/stories that
  // referenced the wiped twins will become orphaned (their character_id
  // keys won't match anything), which is harmless — they just won't
  // appear in any character-scoped list. You can clean them up later
  // or leave them.
  async function resetTwinsOnly() {
    if (!user) {
      alert('Not signed in.')
      return
    }
    const ok = confirm(
      'RESET CHARACTERS ONLY\n\n' +
      'Wipes the character records (the broken Nicks). Keeps your trips, stories, ' +
      'moments, gems, and affinities — but those that referenced the deleted characters ' +
      'will be orphaned (still in the data, just no longer linked to any character).\n\n' +
      'Continue?'
    )
    if (!ok) return
    setIsResetting(true)
    try {
      const current = useStore.getState()
      const partial = {
        characters: current.characters,            // we'll override below
        activeCharacterId: current.activeCharacterId, // override below
        selectedUniverse: current.selectedUniverse,
        storyProgress: current.storyProgress,
        gemBalance: current.gemBalance,
        globalAffinities: current.globalAffinities,
        playthroughHistory: current.playthroughHistory,
        ambientPings: current.ambientPings,
        lastSessionTimestamp: Date.now(),
        castChatThreads: current.castChatThreads,
        unlockedCastIds: current.unlockedCastIds,
        groupCastThreads: current.groupCastThreads,
        favoriteCastIds: current.favoriteCastIds,
        storyMoments: current.storyMoments,
        customCompanions: current.customCompanions,
        travelTrips: current.travelTrips,
        activeTripId: current.activeTripId,
        characters_override: [] as never[],
      }
      // Build the cloud upsert with characters wiped
      const cloudState = { ...partial, characters: [], activeCharacterId: null }
      delete (cloudState as Record<string, unknown>).characters_override
      const { error } = await supabase
        .from('user_game_state')
        .upsert(
          { user_id: user.id, state: cloudState, updated_at: new Date().toISOString() },
          { onConflict: 'user_id' }
        )
      if (error) {
        alert('Reset failed: ' + (error.message ?? 'unknown'))
        setIsResetting(false)
        return
      }
      // Wipe in-memory characters too so the redirect doesn't briefly flash old state
      useStore.setState({ characters: [], activeCharacterId: null })
      try { localStorage.removeItem('chaptr-image-bench-inputs') } catch { /* ITP */ }
      window.location.href = '/home'
    } catch (e) {
      alert('Reset failed: ' + String(e))
      setIsResetting(false)
    }
  }


  // Remixed companions you created. Use the custom uploaded photo if present
  // and not ephemeral; otherwise fall back to the base companion's static
  // portrait so every remix is selectable in the bench.
  const remixOptions = customCompanions
    .map((c) => {
      const customUrl = c.remix.imageUrl && !isEphemeralLike(c.remix.imageUrl) ? c.remix.imageUrl : null
      const base = getTravelCompanion(c.baseId)
      const url = customUrl ?? base?.character.staticPortrait ?? null
      const label = base && base.character.name !== c.remix.name
        ? `${c.remix.name} (remix of ${base.character.name})`
        : c.remix.name
      return url ? { name: label, url } : null
    })
    .filter((o): o is { name: string; url: string } => o !== null)
  const deadRemixNames = customCompanions
    .filter((c) => c.remix.imageUrl && isEphemeralLike(c.remix.imageUrl) && !getTravelCompanion(c.baseId)?.character.staticPortrait)
    .map((c) => c.remix.name)

  // Initial values: prefer localStorage so refresh keeps your test URLs.
  // BUT: if the saved twin URL is ephemeral (dead Together AI) OR the active
  // twin's current selfie differs from what's saved (= you created/switched
  // twins since the last bench run), prefer the live twin selfie. Otherwise
  // the bench would lock onto stale URLs forever.
  const initial = (() => {
    try {
      const raw = localStorage.getItem(BENCH_STORAGE_KEY)
      if (raw) return JSON.parse(raw) as { twinUrl?: string; companionUrl?: string; prompt?: string }
    } catch { /* fall through */ }
    return null
  })()

  const liveTwinUrl = activeChar?.selfieUrl ?? ''
  const savedTwinUrl = initial?.twinUrl ?? ''
  const initialTwinUrl =
    !savedTwinUrl || isEphemeralLike(savedTwinUrl) || (liveTwinUrl && liveTwinUrl !== savedTwinUrl)
      ? liveTwinUrl
      : savedTwinUrl

  const [twinUrl, setTwinUrl] = useState(initialTwinUrl)
  const [companionUrl, setCompanionUrl] = useState(initial?.companionUrl ?? getTravelCompanion('yuna')?.character.staticPortrait ?? '')
  const [prompt, setPrompt] = useState(initial?.prompt ?? DEFAULT_PROMPT)
  const [results, setResults] = useState<Record<ModelId, Result>>({} as Record<ModelId, Result>)
  const [running, setRunning] = useState<Record<ModelId, boolean>>({} as Record<ModelId, boolean>)
  const [selected, setSelected] = useState<Record<ModelId, boolean>>({} as Record<ModelId, boolean>)
  const [previewUrl, setPreviewUrl] = useState<string | null>(null)
  const [view, setView] = useState<'bench' | 'audit'>('bench')
  const [loadedAction, setLoadedAction] = useState<ImageGenAction | null>(null)
  const [uploadingTwin, setUploadingTwin] = useState(false)
  const [twinUploadError, setTwinUploadError] = useState<string | null>(null)
  const twinFileInputRef = useRef<HTMLInputElement>(null)

  // Close modal on ESC
  useEffect(() => {
    if (!previewUrl) return
    const onKey = (e: KeyboardEvent) => { if (e.key === 'Escape') setPreviewUrl(null) }
    window.addEventListener('keydown', onKey)
    return () => window.removeEventListener('keydown', onKey)
  }, [previewUrl])

  // Persist inputs across refresh so the bench survives reloads.
  useEffect(() => {
    try {
      localStorage.setItem(BENCH_STORAGE_KEY, JSON.stringify({ twinUrl, companionUrl, prompt }))
    } catch { /* localStorage may be disabled */ }
  }, [twinUrl, companionUrl, prompt])

  const twinUrlIsEphemeral = !!twinUrl && isEphemeralLike(twinUrl)
  const companionUrlIsEphemeral = !!companionUrl && isEphemeralLike(companionUrl)
  const canResetToActive = !!liveTwinUrl && twinUrl !== liveTwinUrl

  const updateResult = (id: ModelId, r: Result) => setResults((prev) => ({ ...prev, [id]: r }))
  const setBusy = (id: ModelId, b: boolean) => setRunning((prev) => ({ ...prev, [id]: b }))

  // Production accuracy: prod handlers send a specific ref combo (eg. Buy a
  // gift sends companion only, Hold hands sends twin + companion). Always
  // sending both refs in the bench misleads admins — Gemini 2.5 in particular
  // tends to anchor on the first ref it sees, so giving it twin + companion
  // when prod only sends companion produces a wrong-character result that
  // doesn't reflect real behavior. resolveRefs honors the loaded action's
  // references field; without a loaded action it falls through to whatever
  // refs the user has set so free-form testing still works.
  function resolveRefs(): { twinRef: string; companionRef: string } {
    if (!loadedAction) return { twinRef: twinUrl, companionRef: companionUrl }
    switch (loadedAction.references) {
      case 'twin only': return { twinRef: twinUrl, companionRef: '' }
      case 'companion only': return { twinRef: '', companionRef: companionUrl }
      case 'none': return { twinRef: '', companionRef: '' }
      case 'twin + companion':
      default: return { twinRef: twinUrl, companionRef: companionUrl }
    }
  }

  async function runFlux2() {
    setBusy('flux2', true)
    updateResult('flux2', {})
    const t0 = performance.now()
    const { twinRef, companionRef } = resolveRefs()
    const url = await generateSceneImage({
      prompt,
      width: 768,
      height: 576,
      referenceImageUrl: twinRef || undefined,
      companionReferenceUrl: companionRef || undefined,
      includesProtagonist: !!twinRef && !!companionRef,
      protagonistGender: activeChar?.gender,
    })
    const elapsed = performance.now() - t0
    updateResult('flux2', url ? { url, elapsedMs: elapsed } : { error: 'Generation failed', elapsedMs: elapsed })
    setBusy('flux2', false)
  }

  async function runKontext() {
    setBusy('kontext', true)
    updateResult('kontext', {})
    const t0 = performance.now()
    // Kontext path: protagonist ref only, no companion ref
    const url = await generateSceneImage({
      prompt,
      width: 768,
      height: 576,
      referenceImageUrl: twinUrl || undefined,
      includesProtagonist: !!twinUrl,
      protagonistGender: activeChar?.gender,
    })
    const elapsed = performance.now() - t0
    updateResult('kontext', url ? { url, elapsedMs: elapsed } : { error: 'Generation failed', elapsedMs: elapsed })
    setBusy('kontext', false)
  }

  async function runSchnell() {
    setBusy('schnell', true)
    updateResult('schnell', {})
    const t0 = performance.now()
    // Force Schnell by passing no references and includesProtagonist=false
    const url = await generateSceneImage({
      prompt,
      width: 768,
      height: 576,
      includesProtagonist: false,
      protagonistGender: activeChar?.gender,
    })
    const elapsed = performance.now() - t0
    updateResult('schnell', url ? { url, elapsedMs: elapsed } : { error: 'Generation failed', elapsedMs: elapsed })
    setBusy('schnell', false)
  }

  async function runNano(model: ModelId) {
    const apiModel = NANO_MODEL_IDS[model]
    if (!apiModel) return
    setBusy(model, true)
    updateResult(model, {})
    const t0 = performance.now()
    // Resolve relative paths (eg /yuna-portrait.png) to absolute URLs so the
    // Edge proxy can actually fetch them.
    const toAbs = (u: string) => u.startsWith('http') ? u : `${window.location.origin}${u}`
    const { twinRef, companionRef } = resolveRefs()
    const refs = [twinRef, companionRef].filter(Boolean).map(toAbs)
    const result = await generateNanoBananaImage({
      prompt,
      referenceImageUrls: refs,
      model: apiModel,
    })
    const elapsed = performance.now() - t0
    if ('imageDataUrl' in result) {
      updateResult(model, { url: result.imageDataUrl, elapsedMs: elapsed })
    } else {
      updateResult(model, { error: result.error + (result.details ? ` — ${result.details}` : ''), elapsedMs: elapsed })
    }
    setBusy(model, false)
  }

  function runById(id: ModelId) {
    if (id === 'flux2') return runFlux2()
    if (id === 'kontext') return runKontext()
    if (id === 'schnell') return runSchnell()
    return runNano(id)
  }

  function toggleSelected(id: ModelId) {
    setSelected((prev) => ({ ...prev, [id]: !prev[id] }))
  }

  async function runSelected() {
    const ids = (Object.keys(MODEL_LABELS) as ModelId[]).filter((id) => selected[id])
    const targets = ids.length > 0 ? ids : (Object.keys(MODEL_LABELS) as ModelId[])
    targets.forEach((id) => runById(id))
  }

  // Upload a raw photo to Supabase storage so all models (FLUX/Kontext need
  // a public URL — data: URLs won't work for them) can fetch it as a reference.
  async function handleTwinFileUpload(file: File) {
    setTwinUploadError(null)
    setUploadingTwin(true)
    try {
      const dataUrl: string = await new Promise((resolve, reject) => {
        const reader = new FileReader()
        reader.onloadend = () => resolve(reader.result as string)
        reader.onerror = reject
        reader.readAsDataURL(file)
      })
      const path = `bench/raw-${Date.now()}-${Math.random().toString(36).slice(2, 8)}.png`
      const url = await uploadImageToStorage(dataUrl, path)
      if (!url) {
        setTwinUploadError('Upload failed — Supabase rejected the file. Try a smaller image.')
      } else {
        setTwinUrl(url)
      }
    } catch (e) {
      setTwinUploadError(e instanceof Error ? e.message : 'Upload failed')
    } finally {
      setUploadingTwin(false)
    }
  }

  return (
    <div className="min-h-screen min-h-dvh" style={{ background: '#0a0810', fontFamily: SG }}>
      <div className="max-w-[1440px] mx-auto px-5 md:px-8 py-6">
        <button
          onClick={() => navigate('/home')}
          className="cursor-pointer flex items-center gap-1 text-white/40 text-sm mb-6 hover:text-white/70"
        >
          <ChevronLeft size={16} /> Back
        </button>

        <div className="flex items-start justify-between mb-6">
          <div>
            <h1 className="text-white text-3xl font-bold mb-1">Image bench</h1>
            <p className="text-white/40 text-sm">
              Same prompt, same references, every available model. Compare identity match, style, and latency.
            </p>
          </div>
          <button
            onClick={resetTwinsOnly}
            disabled={isResetting}
            className="cursor-pointer flex items-center gap-2 px-4 py-2.5 rounded-lg text-sm font-semibold transition-colors disabled:opacity-50 disabled:cursor-not-allowed shrink-0"
            style={{ background: 'rgba(167,139,250,0.12)', border: '1px solid rgba(167,139,250,0.3)', color: '#c4b5fd' }}
            title="Wipe just the broken character records. Keeps trips, stories, moments, gems."
          >
            {isResetting ? <Loader2 size={14} className="animate-spin" /> : <RefreshCcw size={14} />}
            Reset characters only
          </button>
        </div>

        {/* Tabs */}
        <div className="flex items-center gap-1 mb-6 border-b" style={{ borderColor: '#2a2040' }}>
          <button
            onClick={() => setView('bench')}
            className="cursor-pointer px-4 py-2 text-sm font-semibold transition-colors relative"
            style={{ color: view === 'bench' ? '#fff' : 'rgba(255,255,255,0.4)' }}
          >
            Bench
            {view === 'bench' && <div className="absolute bottom-[-1px] left-0 right-0 h-[2px]" style={{ background: '#c84b9e' }} />}
          </button>
          <button
            onClick={() => setView('audit')}
            className="cursor-pointer px-4 py-2 text-sm font-semibold transition-colors relative"
            style={{ color: view === 'audit' ? '#fff' : 'rgba(255,255,255,0.4)' }}
          >
            Image-gen actions ({IMAGE_GEN_AUDIT.length})
            {view === 'audit' && <div className="absolute bottom-[-1px] left-0 right-0 h-[2px]" style={{ background: '#c84b9e' }} />}
          </button>
        </div>

        {view === 'audit' && (
          <ImageGenAuditView
            onLoadIntoBench={(action) => {
              const samples = action.samplePrompts ?? []
              const initial = samples.length > 0
                ? samples[Math.floor(Math.random() * samples.length)]
                : action.promptTemplate
              setPrompt(initial)
              setLoadedAction(action)
              // Stylize takes a RAW selfie as input — the active twin URL
              // is the already-stylized output. Clear it so user uploads a real photo.
              if (action.feature === 'Stylize twin selfie') {
                setTwinUrl('')
              }
              setView('bench')
            }}
          />
        )}

        {view === 'bench' && loadedAction && (
          <div className="mb-6 p-4 rounded-xl flex items-start justify-between gap-3" style={{ background: 'rgba(200,75,158,0.08)', border: '1px solid rgba(200,75,158,0.3)' }}>
            <div className="min-w-0">
              <p className="text-[#c84b9e] text-[10px] uppercase tracking-widest font-bold mb-1">Currently testing</p>
              <p className="text-white text-sm font-semibold mb-0.5">{loadedAction.feature}</p>
              <p className="text-white/50 text-xs">
                {loadedAction.category} · {loadedAction.trigger} · prod model: <span className="font-mono">{loadedAction.model}</span> · refs: {loadedAction.references}
              </p>
              <p className="text-white/30 text-[11px] font-mono mt-1">{loadedAction.source}</p>
              {loadedAction.references !== 'twin + companion' && (
                <p className="mt-2 text-emerald-300/90 text-[12px] leading-relaxed">
                  🎯 Bench is sending <strong>{loadedAction.references}</strong> to FLUX.2 and Nano Banana models — matching what prod actually sends. The character/companion fields below stay populated, but unused refs are dropped before the API call so identity match reflects real production behavior.
                </p>
              )}
              {loadedAction.samplePrompts && loadedAction.samplePrompts.length > 0 && (
                <p className="mt-2 text-amber-300/90 text-[12px] leading-relaxed">
                  ℹ️ This action's prod prompt is <strong>built dynamically at runtime</strong>. Loaded a representative <strong>sample prompt</strong> ({loadedAction.samplePrompts.length} variant{loadedAction.samplePrompts.length === 1 ? '' : 's'} available) — edit below or shuffle to a different sample.
                </p>
              )}
              {loadedAction.feature === 'Stylize twin selfie' && (
                <p className="mt-2 text-amber-300/90 text-[12px] leading-relaxed">
                  ⚠️ Upload a <strong>raw selfie photo</strong> below — this action transforms a real photo into anime style. Don't use the active character URL (that's already stylized output).
                </p>
              )}
            </div>
            <div className="flex flex-col gap-2 shrink-0">
              {loadedAction.samplePrompts && loadedAction.samplePrompts.length > 1 && (
                <button
                  onClick={() => {
                    const samples = loadedAction.samplePrompts ?? []
                    // Pick any sample that isn't the current one. Falls through
                    // to a random pick if every sample happens to match (eg.
                    // the user edited the prompt back to one of them).
                    const others = samples.filter((s) => s !== prompt)
                    const next = others.length > 0
                      ? others[Math.floor(Math.random() * others.length)]
                      : samples[Math.floor(Math.random() * samples.length)]
                    setPrompt(next)
                  }}
                  className="cursor-pointer text-[10px] uppercase tracking-widest px-3 py-1.5 rounded-md text-[#c84b9e] hover:bg-[rgba(200,75,158,0.12)]"
                  style={{ border: '1px solid rgba(200,75,158,0.4)' }}
                  title={`Shuffle to a different sample (${loadedAction.samplePrompts.length} available)`}
                >
                  🎲 Shuffle sample
                </button>
              )}
              <button
                onClick={() => setLoadedAction(null)}
                className="cursor-pointer text-[10px] uppercase tracking-widest px-3 py-1.5 rounded-md text-white/50 hover:text-white hover:bg-white/5"
                style={{ border: '1px solid rgba(255,255,255,0.15)' }}
              >
                Clear
              </button>
            </div>
          </div>
        )}

        {view === 'bench' && twinUrlIsEphemeral && (
          <div className="mb-6 p-4 rounded-xl flex gap-3 items-start" style={{ background: 'rgba(239,68,68,0.08)', border: '1px solid rgba(239,68,68,0.25)' }}>
            <AlertTriangle size={18} className="text-red-400 shrink-0 mt-0.5" />
            <div>
              <p className="text-red-300 text-sm font-semibold mb-1">Character URL is dead (Together AI ephemeral)</p>
              <p className="text-red-300/70 text-xs leading-relaxed">
                The character selfie URL is <span className="font-mono">api.together.ai/shrt/...</span> — those expire after ~1 hour. FLUX/Kontext won't have a real reference, so identity match will fail.
                Fix: go to <span className="font-mono">/home</span> → click "Upload selfie" → upload a fresh photo. The new URL will be on Supabase storage and persist. Then come back here.
              </p>
            </div>
          </div>
        )}

        {view === 'bench' && (<>
        {/* Debug panel: lists every twin in the store + URL classification.
            Diagnoses "wrong twin is active" vs "active twin's URL is dead" instantly. */}
        {characters.length > 0 && (
          <div className="mb-6 p-4 rounded-xl" style={{ background: 'rgba(124,58,237,0.06)', border: '1px solid rgba(124,58,237,0.15)' }}>
            <p className="text-white/60 text-[11px] uppercase tracking-widest mb-3">Debug — your characters</p>
            <div className="flex flex-col gap-2">
              {characters.map((c) => {
                const isActive = c.id === activeCharId
                const url = c.selfieUrl ?? ''
                const kind = !url
                  ? { label: 'NO SELFIE', color: '#6b7280' }
                  : isEphemeralLike(url)
                    ? { label: 'DEAD (Together AI)', color: '#ef4444' }
                    : url.startsWith('data:')
                      ? { label: 'DATA URL (durable)', color: '#f59e0b' }
                      : url.includes('supabase.co')
                        ? { label: 'SUPABASE (good)', color: '#10b981' }
                        : { label: 'OTHER', color: '#6b7280' }
                return (
                  <div key={c.id} className="flex items-center gap-3 text-xs">
                    {url && !isEphemeralLike(url) ? (
                      <img src={url} alt={c.name} className="w-10 h-10 rounded-lg object-cover shrink-0" />
                    ) : (
                      <div className="w-10 h-10 rounded-lg shrink-0" style={{ background: '#1a1525' }} />
                    )}
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center gap-2">
                        <span className="text-white font-semibold">{c.name}</span>
                        {isActive && <span className="text-[9px] font-bold px-1.5 py-0.5 rounded" style={{ background: '#c84b9e', color: '#fff' }}>ACTIVE</span>}
                        <span className="text-[9px] font-bold px-1.5 py-0.5 rounded" style={{ background: kind.color + '22', color: kind.color }}>{kind.label}</span>
                      </div>
                      <p className="text-white/40 font-mono text-[10px] truncate">{url || '(none)'}</p>
                    </div>
                    {url && (
                      <button
                        onClick={() => setTwinUrl(url)}
                        className="cursor-pointer text-[10px] uppercase tracking-widest text-[#c84b9e] hover:text-[#e060b8] shrink-0"
                      >
                        Use
                      </button>
                    )}
                    <button
                      onClick={() => {
                        if (confirm(`Delete character "${c.name}"? This removes the character and all its trips/stories. Cannot be undone.`)) {
                          deleteCharacter(c.id)
                        }
                      }}
                      className="cursor-pointer p-1 rounded text-red-400/60 hover:text-red-400 hover:bg-red-400/10 shrink-0"
                      title="Delete this character"
                    >
                      <Trash2 size={12} />
                    </button>
                  </div>
                )
              })}
            </div>
            <p className="text-white/30 text-[10px] mt-3 leading-relaxed">
              Tip: if all your characters show DEAD or NO SELFIE, delete them all and create a fresh one at <span className="font-mono text-white/50">/home</span>. The current upload flow stores selfies on Supabase storage and persists them across sessions.
            </p>
          </div>
        )}

        {/* Inputs */}
        <div className="grid md:grid-cols-2 gap-4 mb-4">
          <div>
            <div className="flex items-center justify-between mb-1">
              <label className="text-white/50 text-xs uppercase tracking-widest block">
                Twin selfie URL
                {activeChar?.name && <span className="text-white/30 normal-case ml-2">({activeChar.name})</span>}
              </label>
              <div className="flex items-center gap-3">
                <button
                  onClick={() => twinFileInputRef.current?.click()}
                  disabled={uploadingTwin}
                  className="cursor-pointer flex items-center gap-1 text-[10px] uppercase tracking-widest text-[#c84b9e] hover:text-[#e060b8] disabled:opacity-50"
                >
                  {uploadingTwin ? <Loader2 size={10} className="animate-spin" /> : <Upload size={10} />}
                  {uploadingTwin ? 'Uploading...' : 'Upload photo'}
                </button>
                {canResetToActive && (
                  <button
                    onClick={() => setTwinUrl(liveTwinUrl)}
                    className="cursor-pointer text-[10px] uppercase tracking-widest text-[#c84b9e] hover:text-[#e060b8]"
                  >
                    Use active twin
                  </button>
                )}
              </div>
            </div>
            <input
              ref={twinFileInputRef}
              type="file"
              accept="image/*"
              className="hidden"
              onChange={(e) => {
                const file = e.target.files?.[0]
                if (file) handleTwinFileUpload(file)
                e.target.value = ''
              }}
            />
            <input
              type="text"
              value={twinUrl}
              onChange={(e) => setTwinUrl(e.target.value)}
              placeholder="https://..."
              className="w-full bg-[#13101c] border border-[#2a2040] rounded-lg px-3 py-2 text-white text-sm focus:outline-none focus:border-[#c84b9e]"
            />
            {twinUploadError && (
              <p className="text-red-400/90 text-[11px] mt-1">{twinUploadError}</p>
            )}
            {twinUrl && (
              <button
                type="button"
                onClick={() => setPreviewUrl(twinUrl)}
                className="mt-2 cursor-pointer hover:opacity-80 transition-opacity"
                title="Click to view full size"
              >
                <img src={twinUrl} alt="twin" className="w-20 h-20 rounded-lg object-cover" />
              </button>
            )}
          </div>
          <div>
            <label className="text-white/50 text-xs uppercase tracking-widest mb-1 block">Companion portrait URL</label>
            <div className="flex gap-2 mb-2">
              <select
                value={
                  TRAVEL_COMPANION_OPTIONS.find((o) => o.url === companionUrl)?.url ??
                  remixOptions.find((o) => o.url === companionUrl)?.url ??
                  '__custom__'
                }
                onChange={(e) => {
                  const v = e.target.value
                  if (v !== '__custom__') setCompanionUrl(v)
                }}
                className="flex-1 bg-[#13101c] border border-[#2a2040] rounded-lg px-3 py-2 text-white text-sm focus:outline-none focus:border-[#c84b9e] cursor-pointer"
                style={{ fontFamily: SG }}
              >
                <option value="__custom__">— pick a companion —</option>
                <optgroup label="Travel companions">
                  {TRAVEL_COMPANION_OPTIONS.map((o) => (
                    <option key={o.url} value={o.url}>{o.name}</option>
                  ))}
                </optgroup>
                {remixOptions.length > 0 && (
                  <optgroup label="Your remixes">
                    {remixOptions.map((o) => (
                      <option key={o.url} value={o.url}>{o.name}</option>
                    ))}
                  </optgroup>
                )}
              </select>
            </div>
            {deadRemixNames.length > 0 && (
              <p className="text-amber-300/70 text-[11px] mb-2" style={{ fontFamily: SG }}>
                Hidden ({deadRemixNames.length}): {deadRemixNames.join(', ')} — photo URL expired. Re-upload in /travel.
              </p>
            )}
            <input
              type="text"
              value={companionUrl}
              onChange={(e) => setCompanionUrl(e.target.value)}
              placeholder="/yuna-portrait.png or https://..."
              className="w-full bg-[#13101c] border border-[#2a2040] rounded-lg px-3 py-2 text-white text-sm focus:outline-none focus:border-[#c84b9e]"
            />
            {companionUrlIsEphemeral && (
              <p className="text-red-400/80 text-[11px] mt-1" style={{ fontFamily: SG }}>
                Companion URL is dead (Together AI ephemeral). Re-upload the companion photo, then come back here.
              </p>
            )}
            {companionUrl && (
              <button
                type="button"
                onClick={() => setPreviewUrl(companionUrl)}
                className="mt-2 cursor-pointer hover:opacity-80 transition-opacity"
                title="Click to view full size"
              >
                <img
                  src={companionUrl}
                  alt="companion"
                  className="w-20 h-20 rounded-lg object-cover"
                  onError={(e) => { (e.target as HTMLImageElement).style.opacity = '0.3' }}
                />
              </button>
            )}
          </div>
        </div>

        <div className="mb-4">
          <label className="text-white/50 text-xs uppercase tracking-widest mb-1 block">Prompt</label>
          <textarea
            value={prompt}
            onChange={(e) => setPrompt(e.target.value)}
            rows={4}
            className="w-full bg-[#13101c] border border-[#2a2040] rounded-lg px-3 py-2 text-white text-sm focus:outline-none focus:border-[#c84b9e]"
          />
        </div>

        <div className="flex flex-wrap items-center gap-2 mb-8">
          {(() => {
            const selectedCount = (Object.keys(MODEL_LABELS) as ModelId[]).filter((id) => selected[id]).length
            return (
              <button onClick={runSelected} className="cursor-pointer px-4 py-2 rounded-lg bg-[#c84b9e] text-white text-sm font-semibold">
                {selectedCount === 0 ? 'Run all' : `Run ${selectedCount} selected`}
              </button>
            )
          })()}
          <span className="text-white/30 text-xs px-1">click to select</span>
          {(Object.keys(MODEL_LABELS) as ModelId[]).map((id) => {
            const isSelected = !!selected[id]
            return (
              <button
                key={id}
                onClick={() => toggleSelected(id)}
                className={`cursor-pointer px-3 py-2 rounded-lg text-sm transition-colors border ${
                  isSelected
                    ? 'bg-[#c84b9e]/20 border-[#c84b9e] text-white'
                    : 'bg-[#1a1525] border-[#2a2040] text-white/70 hover:border-[#3d2e5e]'
                }`}
              >
                {SHORT_MODEL_LABELS[id]}
              </button>
            )
          })}
        </div>

        {/* Results grid */}
        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">
          {(Object.keys(MODEL_LABELS) as ModelId[]).map((id) => {
            const r = results[id]
            const isRunning = running[id]
            const cost = MODEL_COST_USD[id]
            return (
              <div key={id} className="rounded-xl overflow-hidden border border-[#2a2040] bg-[#13101c]">
                <div className="aspect-[4/3] flex items-center justify-center bg-[#0a0810] overflow-hidden">
                  {isRunning ? (
                    <Loader2 size={28} className="animate-spin text-white/40" />
                  ) : r?.url ? (
                    <img src={r.url} alt={id} className="w-full h-full object-cover" />
                  ) : r?.error ? (
                    <div className="p-3 max-h-full overflow-y-auto w-full">
                      <p className="text-red-400/80 text-[11px] font-mono whitespace-pre-wrap break-words leading-relaxed">{r.error}</p>
                    </div>
                  ) : (
                    <ImageIcon size={28} className="text-white/15" />
                  )}
                </div>
                <div className="px-3 py-2 border-b border-[#2a2040]/50 flex items-center justify-between text-[11px]">
                  <span className="text-white/40">Latency</span>
                  <span className="text-white/80 font-mono">{r?.elapsedMs ? `${(r.elapsedMs / 1000).toFixed(1)}s` : '—'}</span>
                </div>
                <div className="px-3 py-2 border-b border-[#2a2040]/50 flex items-center justify-between text-[11px]">
                  <span className="text-white/40">Cost / image</span>
                  <span className="text-white/80 font-mono">${cost.toFixed(4)}</span>
                </div>
                <div className="px-3 py-2 border-b border-[#2a2040]/50 flex items-center justify-between text-[11px]">
                  <span className="text-white/40">@ 1k images</span>
                  <span className="text-white/80 font-mono">${(cost * 1000).toFixed(0)}</span>
                </div>
                <div className="px-3 py-2 flex items-center justify-between">
                  <p className="text-white/80 text-xs font-semibold">{MODEL_LABELS[id]}</p>
                  {r?.url && <span className="text-emerald-400/60 text-[10px]">OK</span>}
                  {r?.error && <span className="text-red-400/70 text-[10px]">ERR</span>}
                </div>
              </div>
            )
          })}
        </div>
        </>)}
      </div>

      {previewUrl && (
        <div
          className="fixed inset-0 z-50 flex items-center justify-center p-6 bg-black/85 cursor-zoom-out"
          onClick={() => setPreviewUrl(null)}
        >
          <img
            src={previewUrl}
            alt="full preview"
            className="max-w-full max-h-full rounded-lg shadow-2xl"
            onClick={(e) => e.stopPropagation()}
          />
          <button
            onClick={() => setPreviewUrl(null)}
            className="absolute top-4 right-4 w-9 h-9 rounded-full bg-black/60 hover:bg-black/80 flex items-center justify-center text-white cursor-pointer"
            aria-label="Close preview"
          >
            ✕
          </button>
        </div>
      )}
    </div>
  )
}

/** Multi-color Google "G" mark. Inlined SVG so the audit page can flag
 *  Google-served models (Nano Banana / Gemini) at a glance without pulling
 *  in an icon package. */
function GoogleGIcon({ size = 14 }: { size?: number }) {
  return (
    <svg width={size} height={size} viewBox="0 0 48 48" aria-label="Google" className="shrink-0">
      <path fill="#FFC107" d="M43.611 20.083H42V20H24v8h11.303c-1.649 4.657-6.08 8-11.303 8-6.627 0-12-5.373-12-12s5.373-12 12-12c3.059 0 5.842 1.154 7.961 3.039l5.657-5.657C34.046 6.053 29.268 4 24 4 12.955 4 4 12.955 4 24s8.955 20 20 20 20-8.955 20-20c0-1.341-.138-2.65-.389-3.917z"/>
      <path fill="#FF3D00" d="M6.306 14.691l6.571 4.819C14.655 15.108 18.961 12 24 12c3.059 0 5.842 1.154 7.961 3.039l5.657-5.657C34.046 6.053 29.268 4 24 4 16.318 4 9.656 8.337 6.306 14.691z"/>
      <path fill="#4CAF50" d="M24 44c5.166 0 9.86-1.977 13.409-5.192l-6.19-5.238C29.211 35.091 26.715 36 24 36c-5.202 0-9.619-3.317-11.283-7.946l-6.522 5.025C9.505 39.556 16.227 44 24 44z"/>
      <path fill="#1976D2" d="M43.611 20.083H42V20H24v8h11.303c-.792 2.237-2.231 4.166-4.087 5.571.001-.001.002-.001.003-.002l6.19 5.238C36.971 39.205 44 34 44 24c0-1.341-.138-2.65-.389-3.917z"/>
    </svg>
  )
}

/** Audit-tab view: a categorized list of every image-gen call site in the
 *  app. Each entry shows the trigger, source location, model used,
 *  reference requirements, and the prompt template. "Load into bench"
 *  drops the prompt into the bench page for testing across models. */
function ImageGenAuditView({ onLoadIntoBench }: { onLoadIntoBench: (action: ImageGenAction) => void }) {
  const [categoryFilter, setCategoryFilter] = useState<ImageGenAction['category'] | 'all'>('all')

  const grouped = IMAGE_GEN_AUDIT.reduce((acc, action) => {
    if (!acc[action.category]) acc[action.category] = []
    acc[action.category].push(action)
    return acc
  }, {} as Record<string, ImageGenAction[]>)

  const categoryOrder: ImageGenAction['category'][] = ['Twin', 'Travel', 'Story', 'Chat reaction', 'Cast']

  const categoryColors: Record<ImageGenAction['category'], string> = {
    'Twin': '#c4b5fd',
    'Travel': '#60a5fa',
    'Story': '#fbbf24',
    'Chat reaction': '#f472b6',
    'Cast': '#34d399',
  }

  const refColors: Record<ImageGenAction['references'], string> = {
    'twin + companion': '#a78bfa',
    'twin only': '#60a5fa',
    'companion only': '#fbbf24',
    'none': '#6b7280',
  }

  const visibleCategories = categoryFilter === 'all'
    ? categoryOrder
    : categoryOrder.filter((c) => c === categoryFilter)

  return (
    <div className="flex flex-col gap-6">
      <div className="text-white/50 text-sm leading-relaxed">
        Every place in the app that calls an image-generation model — what triggers it, which model tier runs in production, and the prompt template. Many prompts are built dynamically at runtime (Claude generates them per scene), so where the template is just a description, a representative <span className="text-[#c84b9e]">sample prompt</span> is shown — that's what gets loaded into the bench. Click "Load into bench" to test the prompt across all models.
      </div>

      {/* Category filter chips */}
      <div className="flex flex-wrap items-center gap-2">
        <span className="text-white/40 text-[10px] uppercase tracking-widest mr-1">Filter</span>
        {(['all', ...categoryOrder] as const).map((cat) => {
          const active = categoryFilter === cat
          const count = cat === 'all' ? IMAGE_GEN_AUDIT.length : (grouped[cat]?.length ?? 0)
          const color = cat === 'all' ? '#c84b9e' : categoryColors[cat as ImageGenAction['category']]
          return (
            <button
              key={cat}
              onClick={() => setCategoryFilter(cat)}
              className="cursor-pointer text-[11px] font-semibold px-3 py-1.5 rounded-full transition-colors"
              style={{
                background: active ? color + '22' : 'transparent',
                border: `1px solid ${active ? color : 'rgba(255,255,255,0.12)'}`,
                color: active ? color : 'rgba(255,255,255,0.55)',
              }}
            >
              {cat === 'all' ? 'All' : cat} <span className="opacity-60">({count})</span>
            </button>
          )
        })}
      </div>

      {visibleCategories.map((cat) => {
        const items = grouped[cat]
        if (!items || items.length === 0) return null
        return (
          <div key={cat}>
            <h2
              className="text-sm font-bold uppercase tracking-widest mb-3"
              style={{ color: categoryColors[cat] }}
            >
              {cat} ({items.length})
            </h2>
            <div className="flex flex-col gap-3">
              {items.map((action, i) => (
                <div
                  key={`${cat}-${i}`}
                  className="rounded-xl p-4"
                  style={{ background: '#13101c', border: `1px solid ${categoryColors[action.category]}33` }}
                >
                  <div className="flex items-start justify-between gap-3 mb-2">
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center gap-2 mb-1 flex-wrap">
                        <span
                          className="text-[10px] font-bold px-1.5 py-0.5 rounded uppercase tracking-wider"
                          style={{ background: categoryColors[action.category] + '22', color: categoryColors[action.category] }}
                        >
                          {action.category}
                        </span>
                        <h3 className="text-white text-sm font-semibold">{action.feature}</h3>
                      </div>
                      <p className="text-white/40 text-xs">{action.trigger}</p>
                    </div>
                    <button
                      onClick={() => onLoadIntoBench(action)}
                      className="cursor-pointer text-[10px] uppercase tracking-widest px-3 py-1.5 rounded-md text-[#c84b9e] hover:bg-[rgba(200,75,158,0.1)] shrink-0"
                      style={{ border: '1px solid rgba(200,75,158,0.3)' }}
                    >
                      Load into bench
                    </button>
                  </div>

                  <div className="grid grid-cols-3 gap-2 mb-3">
                    <div>
                      <p className="text-white/30 text-[10px] uppercase tracking-widest mb-0.5">Model</p>
                      <p className="text-white/80 text-xs font-mono flex items-center gap-1.5">
                        {/gemini|nano banana/i.test(action.model) && <GoogleGIcon />}
                        <span>{action.model}</span>
                      </p>
                    </div>
                    <div>
                      <p className="text-white/30 text-[10px] uppercase tracking-widest mb-0.5">References</p>
                      <span className="inline-block text-[10px] font-bold px-1.5 py-0.5 rounded" style={{ background: refColors[action.references] + '22', color: refColors[action.references] }}>
                        {action.references}
                      </span>
                    </div>
                    <div>
                      <p className="text-white/30 text-[10px] uppercase tracking-widest mb-0.5">Source</p>
                      <p className="text-white/60 text-[11px] font-mono break-all">{action.source}</p>
                    </div>
                  </div>

                  <div>
                    <p className="text-white/30 text-[10px] uppercase tracking-widest mb-1">Prompt template</p>
                    <p className="text-white/70 text-xs leading-relaxed font-mono whitespace-pre-wrap" style={{ background: '#0a0810', padding: '8px 10px', borderRadius: 6, border: '1px solid #2a2040' }}>
                      {action.promptTemplate}
                    </p>
                  </div>

                  {action.samplePrompts && action.samplePrompts.length > 0 && (
                    <div className="mt-2">
                      <p className="text-[#c84b9e]/80 text-[10px] uppercase tracking-widest mb-1">
                        {action.samplePrompts.length === 1
                          ? 'Sample prompt (loaded into bench)'
                          : `Sample prompts — ${action.samplePrompts.length} variants (random one loaded; shuffle in bench)`}
                      </p>
                      <div className="flex flex-col gap-1.5">
                        {action.samplePrompts.map((sp, spi) => (
                          <p
                            key={spi}
                            className="text-white/70 text-xs leading-relaxed font-mono whitespace-pre-wrap"
                            style={{ background: '#0a0810', padding: '8px 10px', borderRadius: 6, border: '1px solid rgba(200,75,158,0.3)' }}
                          >
                            {action.samplePrompts!.length > 1 && (
                              <span className="text-[#c84b9e]/60 mr-2">{spi + 1}.</span>
                            )}
                            {sp}
                          </p>
                        ))}
                      </div>
                    </div>
                  )}

                  {action.notes && (
                    <p className="mt-2 text-white/40 text-[11px] leading-relaxed italic">
                      {action.notes}
                    </p>
                  )}
                </div>
              ))}
            </div>
          </div>
        )
      })}
    </div>
  )
}
