import { useNavigate } from 'react-router-dom'
import { ChevronLeft } from 'lucide-react'

const SERIF = "'Playfair Display', Georgia, serif"

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="mb-8">
      <h2 className="text-textPrimary font-semibold text-base mb-3">{title}</h2>
      <div className="text-textSecondary text-sm leading-relaxed space-y-2">{children}</div>
    </div>
  )
}

export function TermsPage() {
  const navigate = useNavigate()

  return (
    <div className="min-h-dvh bg-bg">
      <div className="w-full max-w-[680px] mx-auto px-5 pb-16">
        <div className="pt-10 pb-6 flex items-center gap-3">
          <button
            onClick={() => navigate(-1)}
            className="flex items-center gap-1 text-textSecondary text-sm hover:text-textPrimary transition-colors"
          >
            <ChevronLeft size={16} />
            Back
          </button>
        </div>

        <h1 className="text-textPrimary font-bold text-3xl mb-1" style={{ fontFamily: SERIF }}>
          Terms of Service
        </h1>
        <p className="text-textMuted text-sm mb-10">Last updated: April 2026</p>

        <Section title="1. Acceptance of Terms">
          <p>By accessing or using Chaptr ("the Service"), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service.</p>
          <p>We may update these terms from time to time. Continued use of the Service after changes constitutes acceptance of the updated terms.</p>
        </Section>

        <Section title="2. Description of Service">
          <p>Chaptr is an AI-powered interactive storytelling platform. You create a character, optionally upload a photo, and experience AI-generated narratives across different story universes.</p>
          <p>The Service is provided for personal, non-commercial entertainment purposes only.</p>
        </Section>

        <Section title="3. User Accounts">
          <p>You must sign in with a valid Google account to access the Service. You are responsible for maintaining the security of your account.</p>
          <p>You must be at least 13 years old to use the Service. If you are under 18, you confirm that you have parental or guardian consent.</p>
        </Section>

        <Section title="4. Photo Upload and AI Generation">
          <p>You may optionally upload a photo of yourself to personalise your story experience. By uploading a photo, you confirm that:</p>
          <ul className="list-disc list-inside space-y-1 ml-2">
            <li>You own the rights to the photo or have consent from the person depicted.</li>
            <li>The photo does not contain images of minors.</li>
            <li>You consent to the photo being processed by AI systems to generate a stylised version.</li>
          </ul>
          <p>Your original photo is processed and discarded. Only the AI-generated stylised version may be stored to personalise your story scenes. See our Privacy Policy for details.</p>
        </Section>

        <Section title="5. Content and Conduct">
          <p>You agree not to use the Service to generate, store, or share content that is illegal, harmful, harassing, or otherwise objectionable.</p>
          <p>AI-generated story content is created by language models and does not represent the views of Chaptr. Story content is fictional. Characters are not real people.</p>
        </Section>

        <Section title="6. Intellectual Property">
          <p>The Chaptr platform, including its design, code, and characters, is owned by Chaptr. AI-generated narrative content produced during your session is generated for your personal use.</p>
          <p>You may not reproduce, distribute, or commercialise content generated by the Service without written permission.</p>
        </Section>

        <Section title="7. Limitation of Liability">
          <p>The Service is provided "as is" without warranty of any kind. We are not liable for any indirect, incidental, or consequential damages arising from your use of the Service.</p>
          <p>We do not guarantee that the Service will be uninterrupted, error-free, or that AI-generated content will meet your expectations.</p>
        </Section>

        <Section title="8. Termination">
          <p>We reserve the right to suspend or terminate your access to the Service at any time, for any reason, including violation of these Terms.</p>
        </Section>

        <Section title="9. Governing Law">
          <p>These Terms are governed by the laws of Singapore. Any disputes shall be resolved in the courts of Singapore.</p>
        </Section>

        <Section title="10. Contact">
          <p>For any questions about these Terms, please contact us through the app or at the email address associated with your account.</p>
        </Section>
      </div>
    </div>
  )
}
